### ISSUE TITLE
Combining two classes that are not supposed to be combined

### ISSUE THREAD

**Issue by bisraelsen** [SOM-Research/jsonDiscoverer#6]
Hi, and thanks for making this utility. 

I am getting an unexpected combination of two classes because one contains "type" and "coordinates" and the other contains "type", "id", and "url". You can see in the image that they are combined into a single "geometry" class (second from the left on the bottom row).

![image](https://cloud.githubusercontent.com/assets/3248556/8709980/9fb579d0-2b03-11e5-928a-a9bbdb2e8dab.png)

It is combinind these:
```
"geometry": {
        "type": "Point",
        "coordinates": ["lat", "long", "elev"]
    }
```

```
"identifier" : [
        {"type": "doi",
        "id": "10.1038/nature07717",
        "url": "http://dx.doi.org/10.1038/nature07717"}
        ]
```

**Comment by jlcanovas** [comment]
Thanks for contact us!

I guess the discoverer aggregates both concepts because they share the "type" attribute. However, the resulting concept does not seems to be appropriate.

Let me check the parameters used to combine concepts. I'll report asap.

**Comment by jlcanovas** [comment]
I'm having a look at this issue. To advance faster, coudl you send me the JSON documents you are using? So I can reproduce exactly your problem in my development environment. Thks!

**Comment by jlcanovas** [comment]
Hi @bisraelsen,

I've tried to repricate your problem by creating a couple of JSON examples mirroring yours, however, the generation process seems to be correct:

![source1](https://cloud.githubusercontent.com/assets/1996760/9466707/18244ce0-4b37-11e5-8a66-9bd282472766.jpg)

These are the two JSON files I've used as input:
* https://github.com/SOM-Research/jsonDiscoverer/blob/feature/issue6/jsondiscoverer.zoo/zooMini/issue6/source1/json1.json
* https://github.com/SOM-Research/jsonDiscoverer/blob/feature/issue6/jsondiscoverer.zoo/zooMini/issue6/source1/json2.json

Could you send me the JSON file/s you were using as input?

**Comment by jlcanovas** [comment]
Closed due to lack of more data to be fixed
